[platformio]
default_envs = megaatmega2560

[env]
platform = atmelavr
framework = arduino
monitor_speed = 115200
upload_speed = 115200

[env:megaatmega2560]
board = megaatmega2560

[env:uno]
board = uno

[env:nanoatmega328]
board = nanoatmega328
upload_protocol = arduino

